# Generated by Django 5.2.5 on 2025-10-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_provice_profile_city_province'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provice',
            new_name='Province',
        ),
    ]
