# Generated by Django 5.2.5 on 2025-11-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_provice_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_by_email',
            field=models.BooleanField(default=False),
        ),
    ]
