# Generated by Django 5.2.5 on 2025-10-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_zarinpal_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zarinpal_ref_id',
            field=models.IntegerField(null=True),
        ),
    ]
